services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_USER: ${DB_USER:-myuser}
    ports:
      - "5432:5432"
