spring:
  datasource:
    url: jdbc:postgresql://db:5432/akademika_db
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    database-plaform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: update